# Generated by Django 2.0.5 on 2018-09-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
