# Generated by Django 2.0.5 on 2018-09-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0002_auto_20180928_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archivoDigital.Area'),
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extension',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
