# Generated by Django 2.0.5 on 2018-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0004_auto_20181001_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changePass',
            field=models.BooleanField(default=False, verbose_name='Cambio de password'),
        ),
    ]
