# Generated by Django 2.0.5 on 2018-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivoDigital', '0005_user_changepass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='changePass',
            field=models.CharField(max_length=30, verbose_name='Cambio de password'),
        ),
    ]
